#!/usr/bin/env python
#
import os
import sys
#
# get command line inputs
#
args = sys.argv
nargs = len(args) - 1
if nargs < 1:
    print(f"{args[0]} <yaml_file>\n")
    exit()
yfile = args[1]
basename = yfile.rstrip(".yaml")
yfile2 = basename + "_old001.yaml"
#
# find an available file name to backup the old yaml file
if os.path.exists(yfile2):
    knt = 1
    yfile2 = f'{basename}_old{knt:03}.yaml'
    while os.path.exists(yfile2):
        knt += 1
        yfile2 = f'{basename}_old{knt:03}.yaml'
#
os.replace(yfile, yfile2)
with open(yfile2, 'r') as infile, open(yfile, 'w') as outfile:
    comment_zone = False
    for line in infile:
        # comment out "- filter: Temporal Thinning"
        if "# Duplicate Check" in line:
            comment_zone = True
        elif comment_zone:
            line = "#" + line
            if "reduce obs space" in line:
                comment_zone = False

        outfile.write(line)
